### ISSUE TITLE
NoSuchFieldError: EXPECT_KEYWORD

### ISSUE THREAD

**Issue by hendraanggrian** [shyiko/ktlint#166]
Hi there, thanks for such an amazing ruleset.

I'm using your latest version `0.18.0` and currently experiencing this error:
```
Exception in thread "main" java.lang.NoSuchFieldError: EXPECT_KEYWORD
        at com.github.shyiko.ktlint.ruleset.standard.ModifierOrderRule.<init>(ModifierOrderRule.kt:40)
        at com.github.shyiko.ktlint.ruleset.standard.StandardRuleSetProvider.get(StandardRuleSetProvider.kt:15)
        at com.github.shyiko.ktlint.Main.main(Main.kt:249)
```

Older version `0.15.0` works just fine.

**Comment by shyiko** [comment]
Can you please provide an example (project url?)? My guess would be that you have a conflicting version of kotlin-compiler on the the classpath.

**Comment by hendraanggrian** [comment]
I'm currently writing [this gradle plugin](https://github.com/hendraanggrian/packr-plugin).

That sounds very likely since I'm using the latest Kotlin version `1.2.30`.

**Comment by shyiko** [comment]
Check `./gradlew packr:dependencies` output. It's referencing 1.1.51.

**Comment by hendraanggrian** [comment]
I don't know if it is at all related, but gradle 4.5.1 fixed this issue for me.
