### ISSUE TITLE
NoSuchMethodError 

### ISSUE THREAD

**Issue by crossle** [shyiko/ktlint#195]
ktlint 0.22.0
kotlin 1.2.40
gradle 4.7
```
Exception in thread "Thread-0" java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.jetbrains.kotlin.diagnostics.DiagnosticUtils.getLineAndColumnInPsiFile(Lorg/jetbrains/kotlin/com/intellij/psi/PsiFile;Lorg/jetbrains/kotlin/com/intellij/openapi/util/TextRange;)Lorg/jetbrains/kotlin/diagnostics/PsiDiagnosticUtils$LineAndColumn;
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.github.shyiko.ktlint.Main$parallel$consumer$1.run(Main.kt:669)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.jetbrains.kotlin.diagnostics.DiagnosticUtils.getLineAndColumnInPsiFile(Lorg/jetbrains/kotlin/com/intellij/psi/PsiFile;Lorg/jetbrains/kotlin/com/intellij/openapi/util/TextRange;)Lorg/jetbrains/kotlin/diagnostics/PsiDiagnosticUtils$LineAndColumn;
        at com.github.shyiko.ktlint.ruleset.standard.NoMultipleSpacesRule.getCommentMap(NoMultipleSpacesRule.kt:38)
        at com.github.shyiko.ktlint.ruleset.standard.NoMultipleSpacesRule.visit(NoMultipleSpacesRule.kt:60)
        at com.github.shyiko.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:156)
        at com.github.shyiko.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:36)
        at com.github.shyiko.ktlint.core.KtLint$visitor$2$1.invoke(KtLint.kt:201)
        at com.github.shyiko.ktlint.core.KtLint$visitor$2$1.invoke(KtLint.kt:36)
        at com.github.shyiko.ktlint.core.KtLint.visit(KtLint.kt:492)
        at com.github.shyiko.ktlint.core.KtLint.visit(KtLint.kt:493)
        at com.github.shyiko.ktlint.core.KtLint.visit(KtLint.kt:493)
        at com.github.shyiko.ktlint.core.KtLint.visit(KtLint.kt:493)
        at com.github.shyiko.ktlint.core.KtLint.visit(KtLint.kt:493)
        at com.github.shyiko.ktlint.core.KtLint.visit(KtLint.kt:493)
        at com.github.shyiko.ktlint.core.KtLint.visit(KtLint.kt:493)
        at com.github.shyiko.ktlint.core.KtLint.access$visit(KtLint.kt:36)
        at com.github.shyiko.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:199)
        at com.github.shyiko.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:36)
        at com.github.shyiko.ktlint.core.KtLint.lint(KtLint.kt:151)
        at com.github.shyiko.ktlint.core.KtLint.lint(KtLint.kt:106)
        at com.github.shyiko.ktlint.Main.lint(Main.kt:626)
        at com.github.shyiko.ktlint.Main.access$lint(Main.kt:84)
        at com.github.shyiko.ktlint.Main$main$2.invoke(Main.kt:306)
        at com.github.shyiko.ktlint.Main$main$5$1.call(Main.kt:334)
        at com.github.shyiko.ktlint.Main$main$5$1.call(Main.kt:84)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

**Comment by shyiko** [comment]
Hi. This looks like a classpath issue. Any chance you can provide a complete example / link? `./gradlew app:dependencies` might provide some insight.

**Comment by crossle** [comment]
just test 0.21.0 work well

**Comment by shyiko** [comment]
```sh
$ cat build.gradle 
buildscript {
    ext.kotlin_version = '1.2.40'

    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: "kotlin"

repositories {
    jcenter()
}

configurations {
    ktlint
}

dependencies {
    ktlint "com.github.shyiko:ktlint:0.22.0"
    // additional 3rd party ruleset(s) can be specified here
    // just add them to the classpath (e.g. ktlint 'groupId:artifactId:version') and 
    // ktlint will pick them up
}

task ktlint(type: JavaExec, group: "verification") {
    description = "Check Kotlin code style."
    classpath = configurations.ktlint
    main = "com.github.shyiko.ktlint.Main"
    args "src/**/*.kt"
    // to generate report in checkstyle format prepend following args:
    // "--reporter=plain", "--reporter=checkstyle,output=${buildDir}/ktlint.xml"
    // see https://github.com/shyiko/ktlint#usage for more
}
check.dependsOn ktlint

task ktlintFormat(type: JavaExec, group: "formatting") {
    description = "Fix Kotlin code style deviations."
    classpath = configurations.ktlint
    main = "com.github.shyiko.ktlint.Main"
    args "-F", "src/**/*.kt"
}

$ gradle --version

------------------------------------------------------------
Gradle 4.7
------------------------------------------------------------

Build time:   2018-04-18 09:09:12 UTC
Revision:     b9a962bf70638332300e7f810689cb2febbd4a6c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_74 (Oracle Corporation 25.74-b02)
OS:           Linux 4.9.11-1-ARCH amd64

$ gradle ktlint

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
(elapsed time: 1s)
```
(please check dependency tree)

**Comment by wberlinic** [comment]
I had this problem as well. It was due to my project depending on the 1.2.30 kotlin plugin while ktlint depended upon 1.2.40.  I solved it by downgrading to an older ktlint as I don't see a way to mix the kotlin used by ktlint with the kotlin used by the gradle plugin.
