### ISSUE TITLE
Failed to apply style to Android Studio

### ISSUE THREAD

**Issue by Tapchicoma** [shyiko/ktlint#231]
When running `ktlintApplyToIDEA` gradle task (actually `ktlint --apply-to-idea-project`) from [ktlint-gradle](https://github.com/JLLeitschuh/ktlint-gradle) plugin, following exception happening:
```java
[Fatal Error] :1157:8: XML-Dokumentstrukturen müssen innerhalb derselben Entity beginnen und enden.
Exception in thread “main” org.xml.sax.SAXParseException; lineNumber: 1157; columnNumber: 8; XML-Dokumentstrukturen müssen innerhalb derselben Entity beginnen und enden.
       at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
       at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
       at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
       at com.github.shyiko.ktlint.internal.IntellijIDEAIntegration.enableOptimizeImportsOnTheFlyInsideWorkspace(IntellijIDEAIntegration.kt:177)
       at com.github.shyiko.ktlint.internal.IntellijIDEAIntegration.access$enableOptimizeImportsOnTheFlyInsideWorkspace(IntellijIDEAIntegration.kt:21)
       at com.github.shyiko.ktlint.internal.IntellijIDEAIntegration$apply$updates$2.invoke(IntellijIDEAIntegration.kt:57)
       at com.github.shyiko.ktlint.internal.IntellijIDEAIntegration$apply$updates$2.invoke(IntellijIDEAIntegration.kt:21)
       at com.github.shyiko.ktlint.internal.IntellijIDEAIntegration.apply(IntellijIDEAIntegration.kt:123)
       at com.github.shyiko.ktlint.Main.applyToIDEA(Main.kt:510)
       at com.github.shyiko.ktlint.Main.main(Main.kt:242)
```

Machine environment:
Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3

**Comment by shyiko** [comment]
Hi Yahor. Any chance you can share `<project dir>/.idea/workspace.xml`? This would simplify things.

**Comment by Tapchicoma** [comment]
Hi @shyiko. Here it is:
[workspace.zip](https://github.com/shyiko/ktlint/files/2127386/workspace.zip)

**Comment by shyiko** [comment]
@Tapchicoma workspace.xml appears to be corrupted (it's missing a lot of closing tags, including `</project>`).
